examen/applications/network/urls.py
from django.urls import path
# Importamos las vistas 
from . import views

app_name = "network_app"

urlpatterns = [
     # URL página principal
    path(
         '', 
         views.NetworkMainPageView.as_view(),
         name='main_network',
    ), 
    # URL buscar topología
    path(
         'searchTopology/', 
         views.RegisterRouterView.as_view(),
         name='topology_network',
    ), 
    # URLS para listar datos
    path(
         'listRouters/', 
         views.RouterListView.as_view(),
         name='routers_network',
    ), 
    path(
         'listInterfaces/', 
         views.InterfaceListView.as_view(),
         name='interfaces_network',
    ),
    path(
         'listUsers/', 
         views.SSHUserListView.as_view(),
         name='users_network',
    ),
    path(
         'listRoutersSNMP/', 
         views.SnmpListView.as_view(),
         name='routers_snmp',
    ),
    path(
         'listInterfacesSNMP/', 
         views.SnmpInterfacesListView.as_view(),
         name='interfaces_snmp',
    ),

    path(
         'listPacketLoss/', 
         views.InterfaceLossView.as_view(),
         name='packets_loss',
    ),
    # URLS para actualizar datos en la Base de Datos
    path(
        'updateRouter/<int:pk>/',
        views.RouterUpdateView.as_view(),
        name='update_router'
    ),
    path(
        'updateInterface/<int:pk>/',
        views.InterfaceUpdateView.as_view(),
        name='update_interface'
    ),
    path(
        'updateUser/<int:pk>/',
        views.SSHUserUpdateView.as_view(),
        name='update_user'
    ),

    path(
        'updateRouterSNMP/<int:pk>', 
        views.UpdateRouterSNMPView.as_view(),
        name='update_router_snmp',
    ),  

    # URLS para añadir nuevos registros en la Base de Datos
    path(
        'addUser/',
        views.SSHUserCreateView.as_view(),
        name='add_user'
    ),
    # URLS para eliminar registros en la Base de Datos
    path(
        'deleteUser/<int:pk>/',
        views.SSHUserDeleteView.as_view(),
        name='delete_user'
    ),
]

examen/examen/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
# Importamos los settings
from django.conf import settings
# Importamos los archivos estáticos
from django.conf.urls.static import static

"""
Debemos indicarle a Django que dentro de las urls también considere 
las urls generadas para los archivos multimedia (todo lo que se subirá
dentro del directorio 'media'):
- static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.network.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

examen/applications/network/models.py
from django.db import models

class Router(models.Model):    
    """ Router Model """
    
    ip = models.CharField(
        'IP ID',
         max_length = 20
    )

    host_name = models.CharField(
        'Host Name', 
        max_length = 20
    )

    brand = models.CharField(
        'Brand', 
        max_length = 20
    )

    os = models.CharField(
        'Operative System', 
        max_length = 50
    )

    interfaces_on = models.PositiveIntegerField(null = True)

    # SNMP Fields
    sysName = models.CharField(
        'System Name', 
        max_length = 100, 
        blank = True
    )

    sysLocation = models.CharField(
        'System Location', 
        max_length=50, 
        blank = True
    )

    sysContact  = models.CharField(
        'System Contact', 
        max_length=50, 
        blank = True
    )

    sysDescr = models.CharField(
        'System Description', 
        max_length = 300, 
        blank = True
    )  
    
    def __str__(self):
        return self.host_name


class Interface(models.Model):
    """ Interfaces Model """
    name = models.CharField(
        'Interface Name',
        max_length = 40
    )

    ip = models.CharField(
        'IP',
        max_length = 20
    )

    mask = models.CharField(
        'Mask',
        max_length = 20
    )

    router = models.CharField(
        'Router',
        max_length = 50
    )
    
    # SNMP Fields
    oid = models.CharField(
        'OID Identifier', 
        max_length = 1,
        blank = True
    )

    in_oct = models.CharField(
        'Octetos de Entrada', 
        max_length = 300,
        blank = True
    )

    in_uPackets = models.CharField(
        'Paquetes de Entrada', 
        max_length = 300,
        blank = True
    )

    out_oct = models.CharField(
        'Octetos de Salida', 
        max_length = 300,
        blank = True
    )

    out_uPackets = models.CharField(
        'Paquetes de Salida', 
        max_length = 300,
        blank = True
    )

    times = models.CharField(
        'Time of Last Modification', 
        max_length = 500,
        blank = True
    )

    image = models.ImageField(
        'Image', 
        upload_to ='Interfaces', 
        blank = True
    )

    class Meta:
        ordering = ['id']

    def __str__(self):
        return str(self.id) + '. ' + self.router+' - '+self.name

class SSHUser(models.Model):
    """ SSH User Model """
    username = models.CharField(
        'SSH User Name',
        max_length = 40,
        unique = True
    )

    password = models.CharField(
        'Password',
        max_length = 40
    )
    
    # La llave foránea será el Router
    router = models.ForeignKey( Router, on_delete=models.CASCADE)

    def __str__(self):
        return self.username

examen/applications/network/forms.py
from django import forms

# Los Formularios Simples no trabajan con un modelo en particular
class RouterForm(forms.Form):
    # Validación de la opción elegida 
    valid = forms.BooleanField(
        # El campo debe ser requerido 
        required = True
    )

examen/applications/network/views.py
import os
# Python Local Moducles
from datetime import datetime
from django.core.files import File

# Django Modules
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse_lazy, reverse

# Importamos las funciones propias
from .utils import (
    searchTopology, 
    drawTopologyDiagram, 
    registerSSHUser, 
    make_ssh_conexion, 
    updateHostNames,
    createPlot,
    createPlots
)

from .snmp import snmp_query
# Importamos el formulario que creamos en el archivo forms.py
from .forms import RouterForm
from django.views.generic import (
    TemplateView, 
    ListView,
    UpdateView,
    CreateView,
    DeleteView,
    View
)
from django.views.generic.edit import FormView
# ---> Importamos los modelos necesarios <---
# Importamos el modelo Router y Interface que se encuentra en esta misma aplicación
from .models import Router, Interface, SSHUser

class NetworkMainPageView(TemplateView):
    template_name = "network/home.html"

class RegisterRouterView(FormView):
    """ RegisterRouter """
    template_name = 'network/search.html'
    form_class = RouterForm
    # Lo redirigimos a la página principal
    success_url = reverse_lazy('network_app:main_network')
    # Una vez que los datos ingresados en los inputs del formulario hayan sido validados
    def form_valid(self, form):
        system_name     = '1.3.6.1.2.1.1.5.0' # SysName     OID
        system_location = '1.3.6.1.2.1.1.6.0' # SysLocation OID
        system_contact  = '1.3.6.1.2.1.1.4.0' # SysContact  OID
        system_descr    = '1.3.6.1.2.1.1.1.0' # SysDescr    OID

        print(' ======== FORM VALID ========')
        # Eliminamos los elementos dentro la base de datos
        Router.objects.all().delete()
        Interface.objects.all().delete()
        SSHUser.objects.all().delete()
        # Registramos todos los routers con sus interfaces
        routers_db    = list()
        interfaces_db = list()
        routers = searchTopology()
        # Creating the topology diagram
        drawTopologyDiagram(routers)
        now = datetime.now()
        # Register all the router information in the Database
        for router in routers.keys():
            oid_count = 1
            # Retreiving all the interfaces 
            interfaces = routers[router].get('router_interfaces')
            # Router model instance
            router_id = routers[router].get('router_id')
            router_db = Router(
                ip        = router_id,
                host_name = routers[router].get('router_hostname'),
                brand     = 'Cisco',
                os        = 'Software Version 12.4(25g)',
                interfaces_on = len( interfaces.keys() ),
                sysName     = snmp_query( router_id, system_name ),
                sysLocation = snmp_query( router_id, system_location ),
                sysContact  = snmp_query( router_id, system_contact ),
                sysDescr    = snmp_query( router_id, system_descr )
            )
            routers_db.append(router_db)
            # Defining all the fields for the SNMP Interface
            fa_in_oct       = '1.3.6.1.2.1.2.2.1.10.'
            fa_in_uPackets  = '1.3.6.1.2.1.2.2.1.11.'
            fa_out_oct      = '1.3.6.1.2.1.2.2.1.16.'
            fa_out_uPackets = '1.3.6.1.2.1.2.2.1.17.'

            # Interface model instance
            for interface in interfaces.keys():
                interface_db = Interface(
                    name   = routers[router].get('router_hostname')+'-'+interface,
                    ip     = interfaces[interface].get('ip'),
                    mask   = interfaces[interface].get('mask'),
                    router = routers[router].get('router_hostname')+':'+routers[router].get('router_id'),
                    oid    = str(oid_count),
                    in_oct       = snmp_query( router_id, fa_in_oct+str(oid_count) ) + ',', 
                    in_uPackets  = snmp_query( router_id, fa_in_uPackets+str(oid_count) ) + ',',
                    out_oct      = snmp_query( router_id, fa_out_oct+str(oid_count) ) + ',',
                    out_uPackets = snmp_query( router_id, fa_out_uPackets+str(oid_count) ) + ',',
                    times        = now.strftime('%H:%M:%S') + ','
                )
                interfaces_db.append(interface_db)
                oid_count += 1

            
        # Registramos todos los datos obtenidos en la tabla Router dentro la BD
        Router.objects.bulk_create(
            routers_db
        )
        # Registramos todos los datos obtenidos en la tabla Interface dentro la BD
        Interface.objects.bulk_create(
            interfaces_db
        )
        # Creating the plots for every single interface
        valid = createPlots()
        if valid == 1:
            print('Everything went well')
        else:
            print('Internal Server Error :(')

        print('Todos los registros han sido almacenados correctamente dentro de la Base de Datos')
        return super(RegisterRouterView,self).form_valid(form)

# Vistas para mostrar registros de la Base de Datos

class RouterListView(ListView):
    template_name = "network/list_routers.html"
    context_object_name = 'routers'
    # Al no tener queryset necesitamos especificar el modelo de la BD
    model = Router
    # Ordenamos los datos por id
    ordering = 'id'


class SnmpListView(ListView):
    template_name = 'network/list_snmp.html'
    model = Router
    context_object_name = 'routers'
    ordering = 'host_name'

class SnmpInterfacesListView(ListView):
    template_name = 'network/list_interfaces_snmp.html'
    model = Interface
    ordering = 'router'
    # This function is executed every time that this url is reloaded
    def get_context_data(self, **kwargs):
        context = super(SnmpInterfacesListView, self).get_context_data(**kwargs)
        # Retrieving only the fields in_oct, in_uPackets, out_oct, out_uPackets for all the interfaces in the database
        query_result1 = Interface.objects.values_list('in_oct', 'in_uPackets', 'out_oct', 'out_uPackets')
        # When you retrieve more than one field the following function returns a list of tuples
        query_result2 = Interface.objects.values_list('name', 'times')
        query_result3 = Interface.objects.values_list('id', flat = True)
        
        interfaces_names = []
        for tupla in query_result2:
            name, _ = tupla
            interfaces_names.append( name ) 
        
        inOC_list  = []
        inPA_list  = []
        outOC_list = []
        outPA_list = []

        for tupla in query_result1:
            flat_tuple = tuple(map( lambda number: number.rstrip(',').split(',')[-1], tupla))
            inOC, inPA, outOC, outPA = flat_tuple
            inOC_list.append(inOC) 
            inPA_list.append(inPA) 
            outOC_list.append(outOC)
            outPA_list.append(outPA)
        
        path = '/media/'
        #print(f'Path: {path}')
        query_result4 = Interface.objects.values_list('image', flat=True)
        images = [ f'{path}{image_url}' for image_url in query_result4 ]
        # print(images)
        context['interfaces'] = zip(interfaces_names, inOC_list, inPA_list, outOC_list, outPA_list, images, query_result3)

        return context


    def post( self, request, *args, **kargs ):
        # Recuperamos el id del router que se enviará por la url
        print(f'Entre al método POST en la URL: {self.kwargs}')
        # Defining all the fields for the SNMP Interface
        fa_in_oct       = '1.3.6.1.2.1.2.2.1.10.'
        fa_in_uPackets  = '1.3.6.1.2.1.2.2.1.11.'
        fa_out_oct      = '1.3.6.1.2.1.2.2.1.16.'
        fa_out_uPackets = '1.3.6.1.2.1.2.2.1.17.'
        now = datetime.now()
        interfaces = []
        for interface in Interface.objects.all():
            router = interface.router.split(':')[1]
            oid    = interface.oid
            interface.in_oct       += snmp_query( router, fa_in_oct+str(oid) ) + ','
            interface.in_uPackets  += snmp_query( router, fa_in_uPackets+str(oid) ) + ','
            interface.out_oct      += snmp_query( router, fa_out_oct+str(oid) ) + ','
            interface.out_uPackets += snmp_query( router, fa_out_uPackets+str(oid) ) + ','
            interface.times        += now.strftime('%H:%M:%S') + ','
            interfaces.append(interface)
        
        # Updating all the interfaces
        Interface.objects.bulk_update(
            # Model instances
            interfaces,
            # Fields will be updated
            fields = ['in_oct', 'in_uPackets', 'out_oct', 'out_uPackets', 'times' ]
        )

        valid = createPlots()
        if valid == 1:
            print('Everything went well')
        else:
            print('Internal Server Error :(')

        print('All the interfaces were updated')
        return HttpResponseRedirect(
            reverse(
                'network_app:interfaces_snmp'
            )
        )


class InterfaceLossView(ListView):
    template_name = 'network/list_packets_loss.html'
    model = Interface
    
    def get_context_data(self, **kwargs):
        context = super(InterfaceLossView, self).get_context_data(**kwargs)
        router_4 = Interface.objects.get( name = 'R4-Fa1/1')
        router_6 = Interface.objects.get( name = 'R6-Fa1/0')
        routers = []
        routers.append(router_4)
        routers.append(router_6)
    
        inPA_list  = []
        outPA_list = []
        
        inPA_router_4  = int(router_4.in_uPackets.rstrip(',').split(',')[-1])
        outPA_router_4 = int(router_4.out_uPackets.rstrip(',').split(',')[-1])
        inPA_router_6  = int(router_6.in_uPackets.rstrip(',').split(',')[-1])
        outPA_router_6 = int(router_6.out_uPackets.rstrip(',').split(',')[-1])

        inPA_list.append( inPA_router_4 )
        outPA_list.append( outPA_router_4 )
        inPA_list.append( inPA_router_6 )
        outPA_list.append( outPA_router_6 )

examen/templates/network/add_user.html
<!-- Heredamos todo lo que van a tener en común todos nuestros templates -->
{% extends "base.html" %}
<!-- Cargamos nuestros archivos estáticos que se encuentran en la carpeta 'statics' -->
{% load  static %}
<!-- Title -->
{% block title %}
    Register SSH User
{% endblock title %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h3 class="cell" style="margin-top: 24px; text-align: center;"> Register New SSH User </h3>
            <form class="cell grid-x grid-margin-x align-center" method="POST"> {% csrf_token %}
                <div class="cell large-8">
                    <label> SSH Username:
                        {{ form.username }}
                    </label>
                </div>
                <div class="cell large-8">
                    <label> SSH Password:
                      {{ form.password }}
                    </label>
                </div>
                <div class="cell large-8">
                    <label> Router:
                      {{ form.router }}
                    </label>
                </div>
                <div class="cell" style="text-align: center;">
                    <button type="submit" class="button" style="width: 132px;"> Register </button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

examen/templates/network/delete_user.html
{% extends 'base.html' %}
<!-- Title -->
{% block title %}
    Delete SSH User
{% endblock title %}
<!-- Body -->
{% block content %}
    <!-- Header -->
    {% include 'includes/header.html' %}
    <!-- Content -->
    <div class="grid-container">
        <div class="grid-x" style="margin-top: 24px;">
           <!-- 'object' hace referencia al registro de la BD especificado en la URL por el pk--> 
            <h3 class="cell"> Delete SSH User: {{ object.username }} </h3>
            <form class="cell" method="POST"> {% csrf_token %}
                <div class="callout alert grid-x grid-padding-x">
                    <h5 class="cell large-6"> Do you want to delete this ssh user? </h5>
                    <button type="submit" class="alert button cell large-2"> Delete </button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

examen/templates/network/home.html
<!-- Heredamos todo lo que van a tener en común todos nuestros templates -->
{% extends "base.html" %}
<!-- Cargamos nuestros archivos estáticos que se encuentran en la carpeta 'statics' -->
{% load  static %}
<!-- Title -->
{% block title %}
    Home Page
{% endblock title %}

{% block content %}
    {% include "includes/header.html" %}
    <div style="text-align: center; margin-top: 24px;">
        <h4> Topology </h4>
        <img src="{% static 'img/topology.png' %}"">
    </div>
{% endblock content %}

examen/templates/network/list_interfaces.html
<!-- Heredamos todo lo que van a tener en común todos nuestros templates -->
{% extends "base.html" %}
<!-- Cargamos nuestros archivos estáticos que se encuentran en la carpeta 'statics' -->
{% load  static %}
<!-- Title -->
{% block title %}
    List Interfaces
{% endblock title %}

{% block content %}
    {% include "includes/header.html" %}
    <!-- Content -->
    <div class="grid-container">
        <!-- Creamos un lienzo de Foundation: 12 columnas por sección -->
        <div class="grid-x">
            <div class="cell grid-x">
              <h3 class="cell large-3 "style="margin-top: 24px;"> Interfaces List </h3>
              <a class="cell large-2 button success" href="#" style="margin-top: 24px; color: white;" > Register New </a>
            </div>
            <div class="cell">
                <table>
                    <thead style="background: #81BDA4; color:azure">
                      <tr>
                        <th style="text-align: center;"> INTERFACE NAME </th>
                        <th style="text-align: center;"> IP             </th>
                        <th style="text-align: center;"> MASK           </th>
                        <th style="text-align: center;"> ROUTER         </th>
                        <th style="text-align: center;"> ACTION         </th>
                      </tr>
                    </thead>
                    <tbody style="text-align: center;">
                     {% for interface in interfaces  %}      
                      <tr>
                          <td> {{ interface.name }}   </td>
                          <td> {{ interface.ip }}     </td>
                          <td> {{ interface.mask }}   </td>
                          <td> {{ interface.router }} </td>
                          <td> 
                            <a class="button" href="{% url 'network_app:update_interface' interface.id %}" > Update </a>
                          </td>
                      </tr>
                     {% endfor %}    
                    </tbody>
                  </table>
            </div>
            <!-- Pagination Block -->
            <div class="cell">
                <!-- If there's pagination available -->
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination text-center">
                     <!-- El objeto que es la página actual es page_obj.number-->
                     <!-- Si el bloque de paginación contiene páginas anteriores -->
                      {% if page_obj.has_previous %}
                      <li class="pagination-previous"> 
                        <a href="?page={{page_obj.previous_page_number}}" aria-label="Prev page"> Previous </a>
                      </li> 
                      {% endif %}
                    <!-- Obtenemos el arreglo de páginas que contiene el objeto paginator (es el obj 
                        que manda el ListView)-->
                      {% for page in paginator.page_range  %}
                        <!-- Validamos si nos encontramos en la página actual-->
                        {% ifequal page page_obj.number %} 
                        <!-- Resaltamos la página actual -->
                        <li class="current"><span class="show-for-sr"> You're on page </span>{{page}}</li>
                        <!-- En caso de no encontrarnos en la página actual, simplemente no resaltamos el número de página -->
                        {% else %}
                        <li><a href="?page={{page}}" aria-label="Page"> {{page}} </a></li>
                        {% endifequal %}
                      {% endfor %}
                      <!-- Si el bloque de paginación contiene páginas siguientes -->
                      {% if page_obj.has_next %}
                      <li class="pagination-next">
                          <a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Next</a>
                      </li>
                      {% endif %}
                    </ul>
                  </nav>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}
    

examen/templates/network/list_interfaces_snmp.html
{% extends "base.html" %}

{% load  static %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container" style="margin-top: 24px;">
        <!-- Creamos un lienzo de foundation 12 columnas, con separación entre los elementos
        creados del grid-container -->
        <div class="grid-x grid-margin-x">
            <form method="post" class="cell grid-x" style="margin-bottom: 20px;"> {% csrf_token %}
                <h3 class="cell large-6 large-offset-2" style="text-align: center;" > SNMP Interfaces Information: </h3>
                <button type="submit" class="cell large-2 button alert"> Reload </button>
            </form>
            
            {% for name, inOC, inPA, outOC, outPA, imageUrl, id in interfaces  %}
                <div class="card cell large-4" style="width: 300px;">
                    <div class="card-divider label alert">
                        <h4 class="cell" style="text-align: center;" > {{ name }} </h4>
                    </div>
                    <div class="card-section">
                        <p style="font-weight: bold;"> Octetos de Entrada: </p>
                        <p> {{ inOC }} </p>  
                        <p style="font-weight: bold;"> Paquetes de Entrada: </p>
                        <p> {{ inPA }} </p> 
                        <p style="font-weight: bold;"> Octetos de Salida: </p> 
                        <p> {{ outOC }} </p>
                        <p style="font-weight: bold;"> Paquetes de Salida: </p>   
                        <p> {{ outPA }} </p> 
                        <div style="text-align: center;">
                            <p><button class="button" data-open="modal{{id}}"> View </button></p>
                        </div> 
                    </div>

                    <div class="reveal" id="modal{{id}}" data-reveal style="text-align: center;">
                        <p class="lead"> Statistics Plot - {{ name }} </p>
                        <img src="{{ imageUrl }}">
                        <button class="close-button" data-close aria-label="Close modal" type="button">
                          <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

examen/templates/network/list_routers.html
<!-- Heredamos todo lo que van a tener en común todos nuestros templates -->
{% extends "base.html" %}
<!-- Cargamos nuestros archivos estáticos que se encuentran en la carpeta 'statics' -->
{% load  static %}
<!-- Title -->
{% block title %}
    List Routers
{% endblock title %}

{% block content %}
    {% include "includes/header.html" %}
    <!-- Content -->
    <div class="grid-container">
        <!-- Creamos un lienzo de Foundation: 12 columnas por sección -->
        <div class="grid-x">
            <div class="cell grid-x">
              <h3 class="cell large-3 " style="margin-top: 24px;"> Routers List </h3>
              <a class="cell large-2 button success" href="#" style="margin-top: 24px; color: white;" > Register New </a>
            </div>
            <div class="cell">
                <table>
                    <thead style="background: #81BDA4; color:azure">
                      <tr>
                        <th style="text-align: center;"> ROUTER ID        </th>
                        <th style="text-align: center;"> HOSTNAME         </th>
                        <th style="text-align: center;"> BRAND            </th>
                        <th style="text-align: center;"> OPERATIVE SYSTEM </th>
                        <th style="text-align: center;"> ACTIVE INTERFACES</th>
                        <th style="text-align: center;"> ACTION           </th>
                      </tr>
                    </thead>
                    <tbody style="text-align: center;">
                     {% for router in routers  %}      
                      <tr>
                          <td> {{ router.ip }}            </td>
                          <td> {{ router.host_name }}     </td>
                          <td> {{ router.brand }}         </td>
                          <td> {{ router.os }}            </td>
                          <td> {{ router.interfaces_on }} </td>
                          <td> 
                            <a class="button" href="{% url 'network_app:update_router' router.id %}" > Update </a>
                          </td>
                      </tr>
                     {% endfor %}    
                    </tbody>
                  </table>
            </div>
        </div>
    </div>    
{% endblock content %}

examen/templates/network/list_snmp.html
{% extends "base.html" %}

{% load  static %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container" style="margin-top: 24px;">
        <!-- Creamos un lienzo de foundation 12 columnas, con separación entre los elementos
        creados del grid-container -->
        <div class="grid-x grid-margin-x"> 
            <h3 class="cell" style="text-align: center;" > Router SNMP Information: </h3>
            {% for router in routers  %}
                <div class="card cell large-4" style="width: 300px;">
                    <div class="card-divider label alert">
                        <h4 class="cell" style="text-align: center;" > {{ router.host_name }} </h4>
                    </div>
                    <div class="card-section">
                        <p style="font-weight: bold;"> sysName: </p>
                        <p> {{ router.sysName }} </p>  
                        <p style="font-weight: bold;"> sysLocation: </p>
                        <p> {{ router.sysLocation }} </p> 
                        <p style="font-weight: bold;"> sysContact: </p> 
                        <p> {{ router.sysContact }} </p>
                        <p style="font-weight: bold;"> sysDescription: </p>   
                        <p style="text-align: justify;"> {{ router.sysDescr }} </p>
                        <form method="post"  action="{% url 'network_app:update_router_snmp' router.id %}"> {% csrf_token %}
                            <div style="text-align: center;">
                                <button type="submit" class="button alert"> Reload </button>
                            </div> 
                        </form>
                        
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}
    

examen/templates/network/list_users.html
<!-- Heredamos todo lo que van a tener en común todos nuestros templates -->
{% extends "base.html" %}
<!-- Cargamos nuestros archivos estáticos que se encuentran en la carpeta 'statics' -->
{% load  static %}
<!-- Title -->
{% block title %}
    List SSH Users
{% endblock title %}

{% block content %}
    {% include "includes/header.html" %}
    <!-- Content -->
    <div class="grid-container">
        <!-- Creamos un lienzo de Foundation: 12 columnas por sección -->
        <div class="grid-x">
            <div class="cell grid-x">
              <h3 class="cell large-3 " style="margin-top: 24px;"> SSH Users List </h3>
              <a class="cell large-2 button success" href="{% url 'network_app:add_user' %}" style="margin-top: 24px; color: white;" > Register New </a>
            </div>
            <div class="cell">
                <table>
                    <thead style="background: #81BDA4; color:azure">
                      <tr>
                        <th style="text-align: center;"> USER NAME        </th>
                        <th style="text-align: center;"> ROUTER           </th>
                        <th style="text-align: center;"> ACTION           </th>
                      </tr>
                    </thead>
                    <tbody style="text-align: center;">
                     {% for sshuser in sshusers  %}      
                      <tr>
                          <td> {{ sshuser.username }} </td>
                          <td> {{ sshuser.router }}    </td>
                          <td> 
                            <a class="button" href="{% url 'network_app:update_user' sshuser.id %}" >       Update </a>
                            <a class="button alert" href="{% url 'network_app:delete_user' sshuser.id %}" > Delete </a>
                          </td>
                      </tr>
                     {% endfor %}    
                    </tbody>
                  </table>
            </div>
        </div>
    </div>    
{% endblock content %}