examen/applications/network/urls.py
from django.urls import path
# Importamos las vistas 
from . import views

app_name = "network_app"

urlpatterns = [
     # URL página principal
    path(
         '', 
         views.NetworkMainPageView.as_view(),
         name='main_network',
    ), 
    # URL buscar topología
    path(
         'searchTopology/', 
         views.RegisterRouterView.as_view(),
         name='topology_network',
    ), 
    # URLS para listar datos
    path(
         'listRouters/', 
         views.RouterListView.as_view(),
         name='routers_network',
    ), 
    path(
         'listInterfaces/', 
         views.InterfaceListView.as_view(),
         name='interfaces_network',
    ),
    path(
         'listUsers/', 
         views.SSHUserListView.as_view(),
         name='users_network',
    ),
    path(
         'listRoutersSNMP/', 
         views.SnmpListView.as_view(),
         name='routers_snmp',
    ),
    path(
         'listInterfacesSNMP/', 
         views.SnmpInterfacesListView.as_view(),
         name='interfaces_snmp',
    ),

    path(
         'listPacketLoss/', 
         views.InterfaceLossView.as_view(),
         name='packets_loss',
    ),
    # URLS para actualizar datos en la Base de Datos
    path(
        'updateRouter/<int:pk>/',
        views.RouterUpdateView.as_view(),
        name='update_router'
    ),
    path(
        'updateInterface/<int:pk>/',
        views.InterfaceUpdateView.as_view(),
        name='update_interface'
    ),
    path(
        'updateUser/<int:pk>/',
        views.SSHUserUpdateView.as_view(),
        name='update_user'
    ),

    path(
        'updateRouterSNMP/<int:pk>', 
        views.UpdateRouterSNMPView.as_view(),
        name='update_router_snmp',
    ),  

    # URLS para añadir nuevos registros en la Base de Datos
    path(
        'addUser/',
        views.SSHUserCreateView.as_view(),
        name='add_user'
    ),
    # URLS para eliminar registros en la Base de Datos
    path(
        'deleteUser/<int:pk>/',
        views.SSHUserDeleteView.as_view(),
        name='delete_user'
    ),
]

examen/examen/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
# Importamos los settings
from django.conf import settings
# Importamos los archivos estáticos
from django.conf.urls.static import static

"""
Debemos indicarle a Django que dentro de las urls también considere 
las urls generadas para los archivos multimedia (todo lo que se subirá
dentro del directorio 'media'):
- static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.network.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

examen/templates/includes/header.html
<header>
    <div class="top-bar">
        <div class="top-bar-left">
          <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text"> Network Management Services </li>
            <li> <a href="{% url 'network_app:routers_network' %}">    Routers    </a> </li>
            <li> <a href="{% url 'network_app:interfaces_network' %}"> Interfaces </a> </li>
            <li> <a href="{% url 'network_app:users_network' %}">        Users    </a> </li>
            <li> <a href="{% url 'network_app:topology_network' %}"> Search Topology </a> </li>
            <li> <a href="{% url 'network_app:main_network' %}"> View Topology </a> </li>
            <li> <a href="{% url 'network_app:routers_snmp' %}"> SNMP Routers  </a> </li>
            <li> <a href="{% url 'network_app:interfaces_snmp' %}"> SNMP Interfaces </a> </li>
            <li> <a href="{% url 'network_app:packets_loss' %}"> SNMP Pakcets Loss </a> </li>
          </ul>
        </div>
      </div>
</header>